spring.application.name=shopping-api

server.port=8082

spring.datasource.hikari.connection-timeout=2000
spring.datasource.hikari.maximum-pool-size=5

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.properties.hibernate.default_schema=shopping

spring.flyway.schemas=shopping
spring.flyway.default-schema=shopping