spring.application.name=product-api

server.port=8081

spring.datasource.hikari.connection-timeout=2000
spring.datasource.hikari.maximum-pool-size=5

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.properties.hibernate.default_schema=products

spring.flyway.schemas=products
spring.flyway.default-schema=products